# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 01:51
from __future__ import unicode_literals

import cdms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_id', models.CharField(max_length=100)),
                ('criminal_status', models.CharField(blank=True, choices=[(b'N', b'Normal'), (b'W', b'Wanted'), (b'MW', b'Most Wanted'), (b'US', b'Under Surveillance'), (b'C', b'Convicted'), (b'I', b'Imprisoned'), (b'D', b'Dead')], max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('aliases', models.CharField(blank=True, max_length=1000)),
                ('hair', models.CharField(blank=True, max_length=100)),
                ('eyes', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')], max_length=10)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('scars_and_marks', models.CharField(blank=True, max_length=300)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('crime_titles', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('rewards', models.CharField(blank=True, max_length=1000)),
                ('remarks', models.TextField(blank=True)),
                ('cautions', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cdms.models.PathAndRename('raw', 'criminal'))),
                ('face', models.ImageField(blank=True, null=True, upload_to='faces')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Criminal')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GD_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cdms.models.PathAndRenameForGD('gd_files'))),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name="Mother's Name")),
                ('present_address', models.CharField(blank=True, max_length=300)),
                ('permanent_address', models.CharField(blank=True, max_length=300)),
                ('national_id', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('reading_flag', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.District')),
            ],
        ),
        migrations.CreateModel(
            name='TempImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temps')),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.District')),
            ],
        ),
        migrations.AddField(
            model_name='generaldiary',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Thana'),
        ),
        migrations.AddField(
            model_name='gd_files',
            name='gd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.GeneralDiary'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.District'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Thana'),
        ),
    ]
