# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 01:53
from __future__ import unicode_literals

import cdms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('officer_id', models.CharField(max_length=50)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cdms.models.PathAndRename('pro_pics', 'user'))),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdms.District')),
                ('thana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdms.Thana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
