# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0002_officier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officier',
            name='officer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='officier',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
