# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0003_auto_20170405_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officier',
            old_name='image',
            new_name='pro_pic',
        ),
    ]
