# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0005_auto_20170405_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='is_super_admin',
        ),
        migrations.AddField(
            model_name='officer',
            name='admin_type',
            field=models.CharField(blank=True, choices=[(b'A', b'Admin'), (b'S', b'Super Admin'), (b'OC', b'Officer in Charge')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='area',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Administrative position'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobile numbers'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(choices=[(b'IGP', b'Inspector General of Police'), (b'AIG', b'Additional Inspector General of Police'), (b'DIG', b'Deputy Inspector General of Police'), (b'ADIG', b'Additional Deputy Inspector General of Police'), (b'SP', b'Superintendent of Police'), (b'ASP', b'Additional Superintendent of Police'), (b'SrASP', b'Senior Assistant Superintendent of Police'), (b'AsSP', b'Assistant Superintendent of Police'), (b'I', b'Inspector'), (b'SI', b'Sub Inspector'), (b'ASI', b'Assistant Sub Inspector'), (b'-', b'---------------Metropolitan--------------'), (b'CP', b'Police Commissioner'), (b'ACP', b'Additional Commissioner of Police'), (b'JC', b'Joint Commissioner of Police'), (b'DCP', b'Deputy Police Commissioner'), (b'ADCP', b'Additional Deputy Police Commissioner'), (b'SrAsCP', b'Senior Assistant Police Commissioner'), (b'AsCP', b'Assistant Police Commissioner')], max_length=10),
        ),
    ]
