# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0008_auto_20170411_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='officer_type',
            field=models.CharField(choices=[(b'A', b'Admin'), (b'T', b'Thana'), (b'R', b'Reserve')], default='R', max_length=10),
        ),
    ]
