# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdms', '0009_auto_20170411_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldiary',
            name='reading_flag',
        ),
        migrations.AddField(
            model_name='generaldiary',
            name='action_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generaldiary',
            name='action_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generaldiary',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generaldiary',
            name='stage',
            field=models.CharField(choices=[(b'I', b'Initial'), (b'PRE', b'Pre Action'), (b'POST', b'Post Action')], default='I', max_length=10),
        ),
        migrations.AlterField(
            model_name='officer',
            name='officer_type',
            field=models.CharField(choices=[(b'A', b'Admin'), (b'C', b'Crime'), (b'R', b'Reserve')], default='R', max_length=10),
        ),
    ]
