# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0011_auto_20170419_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldiary',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='generaldiary',
            name='seen_by_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generaldiary',
            name='seen_by_sup',
            field=models.BooleanField(default=False),
        ),
    ]
