# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 09:51
from __future__ import unicode_literals

import cdms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdms', '0012_auto_20170419_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=300, verbose_name='Section of a rule')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('duty_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case_FIR_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cdms.models.PathAndRenameForCase('case_files'))),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Case_Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case_Updates_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cdms.models.PathAndRenameForCase('case_files'))),
                ('case_updates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case_Updates')),
            ],
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name="Mother's Name")),
                ('present_address', models.CharField(blank=True, max_length=300)),
                ('permanent_address', models.CharField(blank=True, max_length=300)),
                ('national_id', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name="Mother's Name")),
                ('present_address', models.CharField(blank=True, max_length=300)),
                ('permanent_address', models.CharField(blank=True, max_length=300)),
                ('criminal_id', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation_Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('assign_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
