# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0013_case_case_fir_files_case_updates_case_updates_files_complainant_defendant_investigation_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='fir_number',
            field=models.CharField(max_length=100, verbose_name='FIR number'),
        ),
        migrations.AlterField(
            model_name='complainant',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case'),
        ),
    ]
