# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0014_auto_20170419_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case_Updates',
            new_name='Case_Update',
        ),
        migrations.RenameModel(
            old_name='Case_Updates_Files',
            new_name='Case_Update_Files',
        ),
        migrations.RenameField(
            model_name='case_update_files',
            old_name='case_updates',
            new_name='case_update',
        ),
        migrations.AddField(
            model_name='case',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cdms.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='thana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cdms.Thana'),
            preserve_default=False,
        ),
    ]
