# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 19:10
from __future__ import unicode_literals

import cdms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdms', '0015_auto_20170419_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of accused')),
                ('aliases', models.CharField(blank=True, max_length=1000, verbose_name='Aliases of accused')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name="Mother's Name")),
                ('present_address', models.CharField(blank=True, max_length=300)),
                ('permanent_address', models.CharField(blank=True, max_length=300)),
                ('accused_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verdict_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cdms.models.PathAndRenameForCase('case_files'))),
                ('case_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case_Update')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(max_length=300, null=True, verbose_name='Location and Distance'),
        ),
        migrations.AddField(
            model_name='case',
            name='reason',
            field=models.CharField(max_length=300, null=True, verbose_name='Why late to file a case'),
        ),
        migrations.AddField(
            model_name='case',
            name='seen_by_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='seen_by_sup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criminal',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='present_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='verdict',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case'),
        ),
        migrations.AddField(
            model_name='charge_sheet',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Case'),
        ),
    ]
