# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0016_auto_20170420_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation_officer',
            name='closing_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
