# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 03:06
from __future__ import unicode_literals

import cdms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0017_investigation_officer_closing_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_sheet',
            name='charges',
            field=models.TextField(null=True, verbose_name='Charges and Specifications'),
        ),
        migrations.AlterField(
            model_name='case_update_files',
            name='file',
            field=models.FileField(upload_to=cdms.models.PathAndRenameForCaseUpdate('case_files')),
        ),
    ]
