# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0018_auto_20170420_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdict',
            name='case',
        ),
        migrations.RemoveField(
            model_name='verdict_files',
            name='case_update',
        ),
        migrations.AddField(
            model_name='verdict_files',
            name='case',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cdms.Case'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Verdict',
        ),
    ]
