# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0020_victim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victim',
            old_name='father_name',
            new_name='vfather_name',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='mobile',
            new_name='vmobile',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='mother_name',
            new_name='vmother_name',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='name',
            new_name='vname',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='national_id',
            new_name='vnational_id',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='permanent_address',
            new_name='vpermanent_address',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='present_address',
            new_name='vpresent_address',
        ),
    ]
