# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdms', '0021_auto_20170423_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal_fir_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir', models.CharField(max_length=100)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdms.Criminal')),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='reason',
            field=models.CharField(max_length=300, null=True, verbose_name='Why late to file a FIR'),
        ),
        migrations.AlterField(
            model_name='complainant',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobile Numbers'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobile Numbers'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='vmobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobile Numbers'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='vname',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='vnational_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='vpermanent_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='vpresent_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Present Address'),
        ),
    ]
